import { Inter, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";
const inter = Inter({ subsets: ["latin"] });
const source_san = Source_Sans_3({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#05060e]">
      <body className={source_san.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
